sudo: required

services:
  - docker

before_install:
  - docker build -t shaheermir/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shaheermir/react-test npm test -- --coverage

after_success:
  - docker build -t shaheermir/multi-client ./client
  - docker build -t shaheermir/multi-nginx ./nginx
  - docker build -t shaheermir/multi-server ./server
  - docker build -t shaheermir/multi-worker ./worker

  # log into  docker cli and push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shaheermir/multi-client
  - docker push shaheermir/multi-nginx
  - docker push shaheermir/multi-server
  - docker push shaheermir/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-970327409342'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
